# Generated by Django 2.2.5 on 2023-04-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_id', models.CharField(max_length=20)),
                ('doc_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_age', models.IntegerField()),
                ('doc_text', models.TextField()),
                ('doc_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=200)),
                ('pat_age', models.IntegerField()),
                ('pat_sex', models.CharField(max_length=20)),
                ('pat_address', models.TextField()),
                ('pat_phone', models.CharField(max_length=200)),
                ('pat_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=100)),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Patient')),
            ],
        ),
    ]
