# Generated by Django 3.2 on 2023-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='img_type',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
