# Generated by Django 3.2 on 2023-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_img_img_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='after_img',
            field=models.TextField(default='null'),
        ),
    ]
