# Generated by Django 3.2 on 2023-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_img_after_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='doc_id',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='img',
            name='propose',
            field=models.TextField(default='暂无'),
        ),
        migrations.AddField(
            model_name='img',
            name='rating',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
