# Generated by Django 3.2 on 2023-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20230405_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20)),
                ('dr_name', models.CharField(max_length=20)),
                ('advice', models.TextField()),
            ],
        ),
    ]
