# Generated by Django 3.2 on 2023-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20230407_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_img',
            field=models.ImageField(default='暂无', upload_to='doc'),
        ),
    ]
