# Generated by Django 3.2 on 2023-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_doctor_doc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img_path',
            field=models.TextField(default='null'),
        ),
    ]
