# Generated by Django 3.2 on 2023-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_doctor_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr',
            name='describe',
            field=models.CharField(default='暂无', max_length=20),
        ),
    ]
